import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  FaExclamationTriangle,
  FaSpinner,
  FaSearch,
} from "react-icons/fa";
import { listPublicLessonPlans, PublicLessonPlan } from "../services/api";
import styles from "../styles/PortalTheme.module.css";

const ALL_GRADES = [
  "All Grades",
  "Preschool",
  "Kindergarten",
  "Grade 1",
  "Grade 2",
  "Grade 3",
  "Grade 4",
  "Grade 5",
  "Grade 6",
  "Grade 7",
  "Grade 8",
  "Grade 9",
  "Grade 10",
  "Grade 11",
  "Grade 12",
  "Senior High School",
];

const ALL_SUBJECTS = [
  "All Subjects",
  "Mathematics",
  "Science",
  "English",
  "Filipino",
  "Araling Panlipunan",
  "MAPEH",
  "Technology and Livelihood Education",
  "Values Education",
];

export default function DiscoverPage() {
  const [plans, setPlans] = useState<PublicLessonPlan[]>([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedSubject, setSelectedSubject] = useState("All Subjects");
  const [selectedGrade, setSelectedGrade] = useState("All Grades");
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("");
  const navigate = useNavigate();

  useEffect(() => {
    listPublicLessonPlans()
      .then(setPlans)
      .catch((err) => setError(err instanceof Error ? err.message : "Failed to load plans"))
      .finally(() => setIsLoading(false));
  }, []);

  const filteredPlans = plans.filter((plan) => {
    const matchesSearch =
      !searchQuery ||
      plan.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      plan.subject.toLowerCase().includes(searchQuery.toLowerCase()) ||
      plan.gradeLevel.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesSubject =
      selectedSubject === "All Subjects" ||
      plan.subject.toLowerCase() === selectedSubject.toLowerCase();
    const matchesGrade =
      selectedGrade === "All Grades" ||
      plan.gradeLevel.toLowerCase() === selectedGrade.toLowerCase();
    return matchesSearch && matchesSubject && matchesGrade;
  });

  function formatDate(dateString: string) {
    const date = new Date(dateString);
    if (Number.isNaN(date.getTime())) return "Recently";
    return date.toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
      year: "numeric",
    });
  }

  return (
    <div className={styles.userAppPage}>
      <header className={styles.userAppHeader}>
        <h1 className={styles.userAppBrand}>Lessora AI</h1>
        <nav className={styles.userAppHeaderActions}>
          <button
            type="button"
            onClick={() => navigate("/generate")}
            className={styles.softSecondary}
          >
            Generate
          </button>
          <button
            type="button"
            onClick={() => navigate("/support")}
            className={styles.softSecondary}
          >
            Support
          </button>
        </nav>
      </header>

      <div className={styles.userAppContainer}>
        <div className={styles.userAppHero}>
          <p className={styles.eyebrow}>Discover</p>
          <h2 className={styles.userAppHeroTitle}>All Lesson Plans</h2>
          <p className={styles.userAppHeroDescription}>
            Explore lesson plans generated by teachers across the platform.
          </p>
        </div>

        <div style={{ display: "flex", gap: 16, flexWrap: "wrap", marginBottom: 24 }}>
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search by title, subject, or grade..."
            className={styles.searchInputLg}
            style={{ flex: 1, minWidth: 200 }}
          />
          <select
            value={selectedSubject}
            onChange={(e) => setSelectedSubject(e.target.value)}
            style={{
              padding: "var(--spacing-3) var(--spacing-4)",
              fontFamily: "var(--font-family-base)",
              fontSize: 14,
              background: "var(--color-surface)",
              border: "1px solid var(--color-rule)",
              borderRadius: 0,
              color: "var(--color-ink-primary)",
              cursor: "pointer",
            }}
          >
            {ALL_SUBJECTS.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
          <select
            value={selectedGrade}
            onChange={(e) => setSelectedGrade(e.target.value)}
            style={{
              padding: "var(--spacing-3) var(--spacing-4)",
              fontFamily: "var(--font-family-base)",
              fontSize: 14,
              background: "var(--color-surface)",
              border: "1px solid var(--color-rule)",
              borderRadius: 0,
              color: "var(--color-ink-primary)",
              cursor: "pointer",
            }}
          >
            {ALL_GRADES.map((g) => (
              <option key={g} value={g}>{g}</option>
            ))}
          </select>
        </div>

        {isLoading && (
          <div className={styles.userAppCenter}>
            <FaSpinner className={styles.userAppIconLarge} style={{ animation: "spin 1s linear infinite" }} />
            <p style={{ margin: 0, fontSize: 16 }}>Loading plans...</p>
          </div>
        )}

        {error && !isLoading && (
          <div className={styles.errorPanel}>
            <FaExclamationTriangle className={styles.userAppIconMedium} />
            <p style={{ margin: "0 0 12px", fontWeight: 600 }}>Failed to load plans</p>
            <p style={{ margin: "0 0 16px", fontSize: 14 }}>{error}</p>
            <button
              type="button"
              onClick={() => window.location.reload()}
              className={styles.softSecondary}
            >
              Try Again
            </button>
          </div>
        )}

        {!isLoading && !error && filteredPlans.length === 0 && plans.length === 0 && (
          <div className={styles.userAppCenter} style={{ background: "var(--color-surface)", border: "1px solid var(--color-border-secondary)", borderRadius: 16 }}>
            <FaSearch className={styles.userAppIconXL} />
            <h3 className={styles.userAppCenterTitle}>No Plans Yet</h3>
            <p className={styles.userAppCenterText} style={{ marginBottom: 24 }}>
              Be the first to generate a lesson plan!
            </p>
            <button
              type="button"
              onClick={() => navigate("/generate")}
              className={styles.flatButton}
            >
              Generate Your First Plan
            </button>
          </div>
        )}

        {!isLoading && !error && filteredPlans.length === 0 && plans.length > 0 && (
          <div className={styles.userAppCenter} style={{ background: "var(--color-surface)", border: "1px solid var(--color-border-secondary)", borderRadius: 16 }}>
            <FaSearch className={styles.userAppIconLarge} style={{ fontSize: 48 }} />
            <h3 className={styles.userAppCenterTitle}>No Results Found</h3>
            <p className={styles.userAppCenterText}>Try a different search term or filter</p>
          </div>
        )}

        {!isLoading && !error && filteredPlans.length > 0 && (
          <div className={styles.planGrid}>
            {filteredPlans.map((plan) => (
              <div
                key={plan.id}
                className={styles.planTile}
                  onClick={() => navigate(`/preview/${plan.id}?public=true`)}
                style={{ cursor: "pointer" }}
              >
                <h3 className={styles.planTileTitle}>{plan.title}</h3>
                <div className={styles.planTileChipRow}>
                  <span className={`${styles.chip} ${styles.chipAccent}`}>
                    {plan.subject}
                  </span>
                  <span className={`${styles.chip} ${styles.chipPurple}`}>
                    {plan.gradeLevel}
                  </span>
                </div>
                <div className={styles.planTileMeta}>
                  <span>{plan.totalDuration} min</span>
                  <span>{formatDate(plan.createdAt)}</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
