import mongoose, { Schema, Document, Types } from "mongoose";

/**
 * Anonymous Session Schema
 * - Tracks unauthenticated users by a random session ID stored client-side
 * - Each session gets 3 free AI generation credits (reset daily)
 * - Sessions expire after 60 days of inactivity
 * - Plans generated by a session are linked by sessionId instead of userId
 */

export interface ISession extends Document {
  _id: mongoose.Types.ObjectId;
  sessionId: string; // UUIDv4, opaque token matching client localStorage
  ip: string;
  userAgent: string;
  aiResponseCredits: number; // starts at 3, refilled daily
  lessonPlanIds: Types.ObjectId[];
  lastActivityAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

const SessionSchema = new Schema<ISession>(
  {
    sessionId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    ip: {
      type: String,
      default: "",
    },
    userAgent: {
      type: String,
      default: "",
    },
    aiResponseCredits: {
      type: Number,
      default: 3,
      min: 0,
    },
    lessonPlanIds: {
      type: [Schema.Types.ObjectId],
      ref: "LessonPlan",
      default: [],
    },
    lastActivityAt: {
      type: Date,
      default: Date.now,
    },
  },
  {
    timestamps: true,
  },
);

// TTL: expire sessions after 60 days of inactivity
SessionSchema.index({ lastActivityAt: 1 }, { expireAfterSeconds: 5_184_000 });

// Compound index for common lookup patterns
SessionSchema.index({ sessionId: 1, aiResponseCredits: 1 });

let SessionModel = mongoose.models.Session as mongoose.Model<ISession> | undefined;
if (!SessionModel) {
  SessionModel = mongoose.model<ISession>("Session", SessionSchema);
}
export const Session = SessionModel;
