import type { Metadata } from 'next';
import openAIService from '@/lib/services/openai.service';

const SITE_URL = process.env.PUBLIC_APP_URL || 'https://lessora.ajgenabio.me';

type PreviewLayoutParams = {
  params: Promise<{ id: string }>;
};

export async function generateMetadata({ params }: PreviewLayoutParams): Promise<Metadata> {
  const { id } = await params;

  try {
    const plan = await openAIService.getPublicLessonPlanById(id);
    const title = `${plan.title} | Lesson Plan`;
    const description = `${plan.subject} lesson plan for ${plan.gradeLevel} (${plan.totalDuration} minutes). Generated by Lessora AI.`;
    return {
      title,
      description,
      alternates: {
        canonical: `/preview/${id}`,
      },
      openGraph: {
        type: 'article',
        url: `/preview/${id}`,
        siteName: 'Lessora AI',
        title,
        description,
        images: [
          {
            url: '/lessora-logo.png',
            width: 512,
            height: 512,
            alt: 'Lessora AI',
          },
        ],
      },
      twitter: {
        card: 'summary',
        title,
        description,
        images: ['/lessora-logo.png'],
      },
      robots: {
        index: true,
        follow: true,
      },
    };
  } catch {
    return {
      title: 'Lesson Plan Preview',
      description: 'Preview a lesson plan generated by Lessora AI.',
      alternates: {
        canonical: `/preview/${id}`,
      },
      robots: {
        index: false,
        follow: true,
      },
    };
  }
}

export default function PreviewLayout({ children }: { children: React.ReactNode }) {
  return children;
}
