import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { cache } from 'react';
import { isValidObjectId } from 'mongoose';
import openAIService from '@/lib/services/openai.service';
import { connectionReady } from '@/lib/db';
import { NotFoundError } from '@/lib/types/errors';
import type { LessonPlanHistoryDetail } from '@/app/lib/api-client';
import PreviewClient from './preview-client';

const SITE_URL = process.env.PUBLIC_APP_URL || 'https://lessora.ajgenabio.me';
const DB_TIMEOUT_MS = 15_000;

type PreviewPageParams = {
  params: Promise<{ id: string }>;
};

// Shared by generateMetadata and the page so one request does one DB lookup.
// Awaiting the connection first matters: on a cold serverless start the query
// used to fail, and the fallback metadata marked every lesson plan noindex.
const getPublicPlan = cache(async (id: string): Promise<LessonPlanHistoryDetail | null> => {
  if (!isValidObjectId(id)) return null;

  await Promise.race([
    connectionReady,
    new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error('MongoDB connection timed out')), DB_TIMEOUT_MS)
    ),
  ]);

  try {
    const plan = await openAIService.getPublicLessonPlanById(id);
    // Plain DTO for the client component (no Mongo/Date objects across the boundary)
    return {
      id: plan.id,
      title: plan.title,
      subject: plan.subject,
      gradeLevel: plan.gradeLevel,
      totalDuration: plan.totalDuration,
      createdAt: new Date(plan.createdAt).toISOString(),
      updatedAt: new Date(plan.updatedAt).toISOString(),
      document: plan.document as LessonPlanHistoryDetail['document'],
      draftText: plan.draftText,
      model: plan.model,
      templateId: plan.templateId as LessonPlanHistoryDetail['templateId'],
    };
  } catch (error) {
    if (error instanceof NotFoundError) return null;
    throw error;
  }
});

export async function generateMetadata({ params }: PreviewPageParams): Promise<Metadata> {
  const { id } = await params;
  const plan = await getPublicPlan(id);

  if (!plan) {
    return {
      title: 'Lesson Plan Not Found',
      robots: {
        index: false,
        follow: true,
      },
    };
  }

  const title = `${plan.title} | Lesson Plan`;
  const description = `${plan.subject} lesson plan for ${plan.gradeLevel} (${plan.totalDuration} minutes). Generated by Lessora AI.`;
  return {
    title,
    description,
    alternates: {
      canonical: `/preview/${id}`,
    },
    openGraph: {
      type: 'article',
      url: `/preview/${id}`,
      siteName: 'Lessora AI',
      title,
      description,
      images: [
        {
          url: '/lessora-logo.png',
          width: 512,
          height: 512,
          alt: 'Lessora AI',
        },
      ],
    },
    twitter: {
      card: 'summary',
      title,
      description,
      images: ['/lessora-logo.png'],
    },
    robots: {
      index: true,
      follow: true,
    },
  };
}

export default async function PreviewPage({ params }: PreviewPageParams) {
  const { id } = await params;
  const plan = await getPublicPlan(id);

  if (!plan) {
    notFound();
  }

  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'LearningResource',
    name: plan.title,
    url: `${SITE_URL}/preview/${plan.id}`,
    learningResourceType: 'Lesson plan',
    educationalLevel: plan.gradeLevel,
    about: plan.subject,
    timeRequired: `PT${plan.totalDuration}M`,
    inLanguage: 'en',
    isAccessibleForFree: true,
    dateCreated: plan.createdAt,
    dateModified: plan.updatedAt,
    publisher: { '@type': 'Organization', name: 'Lessora AI', url: SITE_URL },
  };

  return (
    <>
      <script
        type="application/ld+json"
        // Escape "<" so plan text can never close the script tag
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData).replace(/</g, '\\u003c') }}
      />
      <PreviewClient plan={plan} />
    </>
  );
}
