"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { DownloadSimple } from "@phosphor-icons/react";
import { LessonPlanHistoryDetail, LessonPlanDocumentBlock, ensureSession } from "@/app/lib/api-client";
import SiteHeader from "@/app/components/site-header";
import styles from "@/portal-theme.module.css";

// Lesson text is AI output and must never be interpreted as markup in the export window
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Fixed locale and zone so server and browser render the same string (no hydration mismatch)
function formatCreatedAt(iso: string): string {
  return new Date(iso).toLocaleString("en-PH", { timeZone: "Asia/Manila", dateStyle: "medium", timeStyle: "short" });
}

export default function PreviewClient({ plan }: { plan: LessonPlanHistoryDetail }) {
  const router = useRouter();
  const id = plan.id;
  const [isExporting, setIsExporting] = useState(false);
  const [exportingFormat, setExportingFormat] = useState("");
  const [isNavigatingRefine, setIsNavigatingRefine] = useState(false);

  async function handleExport(format: "pdf" | "docx") {
    try {
      setIsExporting(true);
      setExportingFormat(format.toUpperCase());
      const doc = plan.document;
      const title = escapeHtml(doc.title);
      const accentColor = getComputedStyle(document.documentElement).getPropertyValue('--color-accent').trim() || '#1E3A8A';
      const inkColor = getComputedStyle(document.documentElement).getPropertyValue('--color-ink-primary').trim() || '#111111';
      const secondaryColor = getComputedStyle(document.documentElement).getPropertyValue('--color-ink-secondary').trim() || '#4B5563';
      const tertiaryColor = getComputedStyle(document.documentElement).getPropertyValue('--color-ink-tertiary').trim() || '#6B7280';
      const ruleColor = getComputedStyle(document.documentElement).getPropertyValue('--color-rule').trim() || '#E7E5DF';
      const headerHtml = `<div style="font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px;"><h1 style="font-size: 24px; color: ${accentColor}; border-bottom: 2px solid ${accentColor}; padding-bottom: 12px; margin-bottom: 24px;">${title}</h1><p style="color: ${secondaryColor}; font-size: 13px; margin-bottom: 24px;">Subject: ${escapeHtml(plan.subject)} | Grade: ${escapeHtml(plan.gradeLevel)} | Duration: ${plan.totalDuration} min</p>`;
      const footerHtml = `<p style="font-size: 11px; color: ${tertiaryColor}; margin-top: 40px; border-top: 1px solid ${ruleColor}; padding-top: 16px;">Generated by Lessora AI</p></div>`;
      const blocksHtml = doc.blocks.map((block) => {
        if (block.type === "heading") {
          const tag = `h${block.level}`;
          const size = block.level === 1 ? "20px" : block.level === 2 ? "17px" : "15px";
          return `<${tag} style="font-size: ${size}; color: ${inkColor}; margin: 20px 0 10px; font-weight: 700;">${escapeHtml(block.text)}</${tag}>`;
        }
        if (block.type === "paragraph") {
          return `<p style="font-size: 14px; line-height: 1.7; color: ${inkColor}; margin: 0 0 14px;">${escapeHtml(block.text)}</p>`;
        }
        if (block.type === "list") {
          const Tag = block.style === "numbered" ? "ol" : "ul";
          const items = block.items.map((item) => `<li style="font-size: 14px; line-height: 1.6; margin-bottom: 6px;">${escapeHtml(item)}</li>`).join("");
          return `<${Tag} style="padding-left: 24px; margin: 0 0 16px; font-size: 14px; color: ${inkColor};">${items}</${Tag}>`;
        }
        return "";
      }).join("");
      const html = `${headerHtml}${blocksHtml}${footerHtml}`;
      if (format === "pdf") {
        const printWindow = window.open("", "_blank");
        if (printWindow) {
          printWindow.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>body{margin:0;}</style></head><body>${html}</body></html>`);
          printWindow.document.close();
          printWindow.focus();
          printWindow.print();
          printWindow.close();
        }
      } else {
        const blob = new Blob([`<html><head><meta charset="utf-8"><title>${title}</title></head><body>${html}</body></html>`], { type: "application/msword" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${doc.title.replace(/\s+/g, "_")}.doc`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
      }
    } catch (err) {
      console.error("Export failed:", err);
    } finally {
      setIsExporting(false);
      setExportingFormat("");
    }
  }

  async function handleNavigateToRefine() {
    if (isNavigatingRefine) return;
    setIsNavigatingRefine(true);
    try {
      // Sessions are created only when a visitor actually wants to use AI, not on every page view
      await ensureSession();
      router.push(`/refine/${id}`);
    } catch (err) {
      console.error("Could not start a session:", err);
      setIsNavigatingRefine(false);
    }
  }

  function renderBlock(block: LessonPlanDocumentBlock, index: number) {
    if (block.type === "heading") {
      const headingClass = block.level === 1 ? styles.planBlockHeading1 : block.level === 2 ? styles.planBlockHeading2 : styles.planBlockHeading3;
      // The plan title above is the page's <h1>; document headings start at <h2> (same visual class)
      const HeadingTag = `h${Math.min(block.level + 1, 4)}` as keyof JSX.IntrinsicElements;
      return <HeadingTag key={index} className={headingClass}>{block.text}</HeadingTag>;
    }
    if (block.type === "paragraph") return <p key={index}>{block.text}</p>;
    if (block.type === "list") {
      const ListTag = block.style === "numbered" ? "ol" : "ul";
      return <ListTag key={index}>{block.items.map((item: string, i: number) => <li key={i}>{item}</li>)}</ListTag>;
    }
    return null;
  }

  return (
    <div className={styles.userAppPage}>
      <SiteHeader />

      <main className={styles.userAppContainerNarrow}>
        <section className={styles.pageHead}>
          <p className={styles.metaLine}>{plan.subject} · {plan.gradeLevel} · {plan.totalDuration} minutes</p>
          <h1 className={styles.pageTitle}>{plan.title}</h1>
          <p className={styles.planCardMeta}>Created {formatCreatedAt(plan.createdAt)}</p>
        </section>

        <article className={styles.planDocument}>
          {plan.document.blocks.map((block, index) => renderBlock(block, index))}
        </article>

        <div className={styles.actionRow}>
          <button type="button" onClick={handleNavigateToRefine} className={styles.flatButton} disabled={isNavigatingRefine} aria-busy={isNavigatingRefine}>{isNavigatingRefine ? "Opening…" : "Refine this plan"}</button>
          <button type="button" onClick={() => handleExport("pdf")} className={styles.softSecondary} disabled={isExporting} aria-busy={isExporting && exportingFormat === "PDF"}><DownloadSimple weight="bold" size={16} /> {isExporting && exportingFormat === "PDF" ? "Preparing…" : "Download PDF"}</button>
          <button type="button" onClick={() => handleExport("docx")} className={styles.softSecondary} disabled={isExporting} aria-busy={isExporting && exportingFormat === "DOCX"}><DownloadSimple weight="bold" size={16} /> {isExporting && exportingFormat === "DOCX" ? "Preparing…" : "Download Word"}</button>
          <a href="/generate" className={styles.softSecondary}>Start a new plan</a>
        </div>
      </main>
    </div>
  );
}
